
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_240


//CONFIG_FREERTOS_UNICORE=n
#define CONFIG_FREERTOS_HZ 500
  
/*  
#
# Partition Table
#
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv"
CONFIG_PARTITION_TABLE_FILENAME="partitions.csv"
*/


#define CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS
#define CONFIG_FREERTOS_RUN_TIME_STATS_USING_ESP_TIMER


#define CONFIG_ESPTOOLPY_FLASHSIZE_4MB
#define CONFIG_FLASHMODE_QIO
#define CONFIG_ESPTOOLPY_FLASHFREQ_80M
#define CONFIG_LWIP_IRAM_OPTIMIZATION

#define CONFIG_LEFT_CHANNEL_GPIO 25
#define CONFIG_RIGHT_CHANNEL_GPIO 26
